---
# The ovnconfig config file. Used by both node and master processes.
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovnkube-config
  namespace: openshift-ovn-kubernetes
data:
  ovnkube.conf:   |-
    [default]
    mtu="{{.MTU}}"
    {{- if .RoutableMTU }}
    routable-mtu="{{.RoutableMTU}}"
    {{- end }}
    cluster-subnets="{{.OVN_cidr}}"
    encap-port="{{.GenevePort}}"
    enable-lflow-cache=true
    lflow-cache-limit-kb=1048576
    enable-udp-aggregation={{.EnableUDPAggregation}}

    [kubernetes]
    service-cidrs="{{.OVN_service_cidr}}"
    ovn-config-namespace="openshift-ovn-kubernetes"
    apiserver="{{.K8S_APISERVER}}"
    host-network-namespace="openshift-host-network"
{{- if .OVNHybridOverlayEnable }}
    no-hostsubnet-nodes="kubernetes.io/os=windows"
{{- end  }}
{{- if .IsNetworkTypeLiveMigration }}
    no-hostsubnet-nodes="migration.network.openshift.io/plugin="
{{- end }}
    platform-type="{{.PlatformType}}"
    healthz-bind-address="0.0.0.0:10256"
    dns-service-namespace="openshift-dns"
    dns-service-name="dns-default"
 
    [ovnkubernetesfeature]
    enable-egress-ip=true
    enable-egress-firewall=true
    enable-egress-qos=true
    enable-egress-service=true
    {{- if .ReachabilityTotalTimeoutSeconds }}
    egressip-reachability-total-timeout={{.ReachabilityTotalTimeoutSeconds}}
    {{- end }}
{{- if .ReachabilityNodePort }}
    egressip-node-healthcheck-port={{.ReachabilityNodePort}}
{{- end }}
{{- if .OVN_MULTI_NETWORK_ENABLE }}
    enable-multi-network=true
{{- end }}
{{- if .OVN_MULTI_NETWORK_POLICY_ENABLE }}
    enable-multi-networkpolicy=true
{{- end }}
{{- if .OVN_ADMIN_NETWORK_POLICY_ENABLE }}
    enable-admin-network-policy=true
{{- end }}
    enable-multi-external-gateway=true
{{- if .DNS_NAME_RESOLVER_ENABLE }}
    enable-dns-name-resolver=true
{{- end }}

    [gateway]
    mode={{.OVN_GATEWAY_MODE}}
    nodeport=true
{{- if (index . "V4InternalMasqueradeSubnet")}}
    v4-masquerade-subnet="{{.V4InternalMasqueradeSubnet}}"
{{- end }}
{{- if (index . "V6InternalMasqueradeSubnet")}}
    v6-masquerade-subnet="{{.V6InternalMasqueradeSubnet}}"
{{- end }}

    [logging]
    libovsdblogfile=/var/log/ovnkube/libovsdb.log
    logfile-maxsize=100
    logfile-maxbackups=5
    logfile-maxage=0
{{- if or .OVNHybridOverlayEnable .IsNetworkTypeLiveMigration}}

    [hybridoverlay]
    enabled=true
    {{- if .OVNHybridOverlayNetCIDR }}
    cluster-subnets="{{.OVNHybridOverlayNetCIDR}}"
    {{- end }}
    {{- if .OVNHybridOverlayVXLANPort}}
    hybrid-overlay-vxlan-port="{{.OVNHybridOverlayVXLANPort}}"
    {{- end }}
{{- end  }}
{{- if .IsSNO }}

    [clustermgrha]
    {{- /* 
    Even in case of SNO there will be only one ovn-master, we set dedicated values for leader election 
    durations in SNO, as disabling it can cause issues on scaling out SNO again. 
    The whole discussion can be found at https://coreos.slack.com/archives/CDCP2LA9L/p1627402405090600. 
    Recommended values at https://github.com/openshift/enhancements/blame/84e894ead7b188a1013556e0ba6973b8463995f1/CONVENTIONS.md#L183
    */}}
    election-lease-duration=137
    election-renew-deadline=107
    election-retry-period=26
{{- end  }}
