# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  # Had to add this since I was getting golang panics: https://github.com/golang/dep/issues/1799
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.0"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

  [[prune.project]]
    name = "github.com/openshift/api"
    non-go = false
    unused-packages = true

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "^2"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/openshift/api"

[[constraint]]
  name = "k8s.io/kube-proxy"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  revision="2567326a4c71208f8b4717a784a912212b5eff7d"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "0.7.1"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  revision = "2df793d0207600b5cd3a50be2d3edd7f5cb333d9"

[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.3"
