apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-network-operator
  namespace: openshift-cluster-network-operator
  labels:
    k8s-app: cluster-network-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cluster-network-operator
  template:
    metadata:
      labels:
        k8s-app: cluster-network-operator
    spec:
      containers:
      - name: cluster-network-operator
        image: docker.io/openshift/origin-cluster-network-operator:v4.0.0
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
        env:
        - name: NODE_IMAGE
          value: "docker.io/openshift/origin-node:v4.0.0-local"
        - name: HYPERSHIFT_IMAGE
          value: "docker.io/openshift/origin-hypershift:v4.0.0-local"
        - name: KUBERNETES_SERVICE_PORT # allows CVO to communicate with apiserver directly on same host.
          value: "6443"
        - name: KUBERNETES_SERVICE_HOST # allows CVO to communicate with apiserver directly on same host.
          value: "127.0.0.1"
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: Exists
        effect: NoSchedule
