# These are the CredentialsRequests for the cloud-network-config-controller,
# NOT the CNO directly. Rather, CredentialsRequests need to be part of the
# install payload (in /manifests), so that administrators can manually
# provision them - see
# https://github.com/openshift/enhancements/blob/master/enhancements/installer/credentials-management-outside-openshift-cluster.md
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-cloud-network-config-controller-gcp
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  serviceAccountNames:
    - cloud-network-config-controller
  secretRef:
    name: cloud-credentials
    namespace: openshift-cloud-network-config-controller
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    permissions:
      - compute.instances.updateNetworkInterface
      - compute.subnetworks.use
      - compute.subnetworks.get
      - compute.zoneOperations.get
      - compute.instances.get
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-cloud-network-config-controller-aws
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  serviceAccountNames:
    - cloud-network-config-controller
  secretRef:
    name: cloud-credentials
    namespace: openshift-cloud-network-config-controller
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - ec2:DescribeInstances
      - ec2:DescribeInstanceStatus
      - ec2:DescribeInstanceTypes
      - ec2:UnassignPrivateIpAddresses
      - ec2:AssignPrivateIpAddresses
      - ec2:UnassignIpv6Addresses
      - ec2:AssignIpv6Addresses
      - ec2:DescribeSubnets
      - ec2:DescribeNetworkInterfaces
      resource: "*"
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-cloud-network-config-controller-azure
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  serviceAccountNames:
    - cloud-network-config-controller
  secretRef:
    name: cloud-credentials
    namespace: openshift-cloud-network-config-controller
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    permissions:
    - Microsoft.Network/networkInterfaces/read
    - Microsoft.Network/networkInterfaces/write
    - Microsoft.Compute/virtualMachines/read
    - Microsoft.Network/virtualNetworks/read
    - Microsoft.Network/virtualNetworks/subnets/join/action
    - Microsoft.Network/loadBalancers/backendAddressPools/join/action
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-cloud-network-config-controller-openstack
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  serviceAccountNames:
    - cloud-network-config-controller
  secretRef:
    name: cloud-credentials
    namespace: openshift-cloud-network-config-controller
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
