apiVersion: v1
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {}
    http {
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;
      server {
        listen              9443 ssl;
        ssl_certificate     /var/cert/tls.crt;
        ssl_certificate_key /var/cert/tls.key;
        root                /opt/app-root/src;

        # Prevent caching for plugin-manifest.json
        location = /plugin-manifest.json {
          add_header Cache-Control 'no-cache, no-store, must-revalidate, proxy-revalidate, max-age=0';
          add_header Pragma 'no-cache';
          add_header Expires '0';
        }

        # Prevent caching for plugin-entry.js
        location = /plugin-entry.js {
          add_header Cache-Control 'no-cache, no-store, must-revalidate, proxy-revalidate, max-age=0';
          add_header Pragma 'no-cache';
          add_header Expires '0';
        }
      }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: networking-console-plugin
    app.kubernetes.io/managed-by: cluster-network-operator
    app.kubernetes.io/name: networking-console-plugin
    app.kubernetes.io/part-of: cluster-network-operator
  name: networking-console-plugin
  namespace: openshift-network-console
