---
# The network cidr and service cidr are set in the ovn-config configmap
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-config
  namespace: openshift-ovn-kubernetes
data:
  net_cidr:   {{.OVN_cidr}}
  svc_cidr:   {{.OVN_service_cidr}}
